name: lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: golang
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          make godeps
          make dependencies
          make common

      - name: golangci
        uses: golangci/golangci-lint-action@v1
        env:
          GOPATH: /home/runner/work/nextcloud-spreed-signaling/nextcloud-spreed-signaling/vendor:/home/runner/work/nextcloud-spreed-signaling/nextcloud-spreed-signaling
        with:
          version: v1.29
          args: ./src/...
